# Generated by Django 3.0.4 on 2020-03-23 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sims', '0002_auto_20200323_2247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='level',
            name='flow',
        ),
    ]
