# Generated by Django 3.0.4 on 2020-03-23 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sims', '0003_remove_level_flow'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Level',
        ),
        migrations.AddField(
            model_name='flow',
            name='content',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
