# Generated by Django 3.0.4 on 2020-03-23 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sims', '0004_auto_20200323_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flow',
            name='content',
            field=models.TextField(default=''),
        ),
    ]
