# Generated by Django 3.0.4 on 2020-04-27 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sims', '0005_auto_20200323_2305'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimProp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flow', models.TextField(default='')),
                ('cosmic_end', models.CharField(choices=[('PostSN', 'PostSN'), ('CO+He', 'CO+He')], max_length=20)),
                ('cosmic_evolve_dict', models.TextField(default='')),
                ('mesa_mechanism', models.CharField(choices=[('Fryer+12-rapid', 'Fryer+12-rapid'), ('Fryer+12-delayed', 'Fryer+12-delayed'), ('Fryer+12-delayed-full_kicks', 'Fryer+12-delayed-full_kicks'), ('direct', 'direct'), ('Sukhbold+16-N20-engine', 'Sukhbold+16-N20-engine')], max_length=40)),
                ('mesa_sigma_kick', models.DecimalField(decimal_places=3, max_digits=6)),
                ('mesa_phi', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('mesa_cos_theta', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('mesa_mean_anomaly', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('mesa_mass_central_BH', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('mesa_neutrino_mass_loss_fraction', models.DecimalField(decimal_places=3, max_digits=6)),
                ('mesa_neutrino_AM_loss', models.BooleanField()),
                ('mesa_PISN', models.CharField(blank=True, default='None', max_length=20)),
                ('mesa_log_scale', models.BooleanField()),
                ('mesa_verbose', models.BooleanField()),
                ('max_time', models.FloatField()),
            ],
        ),
    ]
