# Generated by Django 3.0.4 on 2020-04-27 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sims', '0007_simprop_step_end'),
    ]

    operations = [
        migrations.AddField(
            model_name='simprop',
            name='title',
            field=models.CharField(default='simprop', max_length=30),
            preserve_default=False,
        ),
    ]
