# Generated by Django 3.0.4 on 2020-05-05 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sims', '0008_simprop_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='simprop',
            old_name='mesa_neutrino_mass_loss_fraction',
            new_name='mesa_neutrino_mass_loss',
        ),
        migrations.RemoveField(
            model_name='simprop',
            name='mesa_cos_theta',
        ),
        migrations.RemoveField(
            model_name='simprop',
            name='mesa_mean_anomaly',
        ),
        migrations.RemoveField(
            model_name='simprop',
            name='mesa_neutrino_AM_loss',
        ),
        migrations.RemoveField(
            model_name='simprop',
            name='mesa_phi',
        ),
        migrations.AddField(
            model_name='simprop',
            name='mesa_metallicity',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='simprop',
            name='max_time',
            field=models.FloatField(default=0),
        ),
    ]
