# Generated by Django 3.0.4 on 2020-05-05 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sims', '0009_auto_20200505_1608'),
    ]

    operations = [
        migrations.RenameField(
            model_name='simprop',
            old_name='mesa_metallicity',
            new_name='metallicity',
        ),
    ]
