# Generated by Django 3.0.4 on 2020-05-20 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sims', '0010_auto_20200505_1641'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Flow',
        ),
    ]
